//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SozlukApp.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserEntry
    {
        public int UserEntryId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> EntryId { get; set; }
        public Nullable<byte> LikeStatus { get; set; }
    }
}
